config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :registrations => "registrations" }

resources :conversations, only: [:index, :show, :destroy] do
     member do
       post :reply
       post :restore
       post :mark_as_read
     end
     collection do
       delete :empty_trash
     end
end

 resources :users, only: [:index]

 resources :messages, only: [:new, :create]

 resources :works, only: [:show, :index] do
   resources :resumes, only: [:new, :create]
 end

 resources :applies, only: [:new, :create]

  namespace :company do
    resources :works do
      resources :resumes
    end
  end

  resources :notifications, only: [] do
    member do
      get :redirect_notification
    end
  end

  namespace :admin do
    resources :applies, only: [:index, :show, :destroy] do
      member do
        post :failed
        post :passing
        post :application
      end
    end
    resources :works do
      member do
        post :publish
        post :hide
      end
    end
    resources :users, only: [:index, :show, :destroy] do
      member do
        post :admin
        post :user
      end
    end
  end

  root "works#index"

end

app/models/work.rb
class Work < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}
  has_many :resumes, dependent: :destroy
  has_many :notifications, as: :notifiable
  belongs_to :user
end

app/controllers/admin/works_controller.rb
class Admin::WorksController < ApplicationController
  before_filter :require_is_admin
  before_action :authenticate_user!
  before_action :get_notification
  layout "admin"
  def index
    @works = Work.all
  end

  def show
    @work = Work.find(params[:id])
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    if @work.update(work_params)
      redirect_to company_work_path(@work)
    else
      render :edit
    end
  end

    def destroy
      @work = Work.find(params[:id])
      @work.destroy
      redirect_to company_works_path
    end

    def publish
    @work = work.find(params[:id])
    @work.is_hidden = false
    @work.save
    redirect_to :back
  end

  def hide
    @work = work.find(params[:id])
    @work.is_hidden = true
    @work.save
    redirect_to :back
  end

  private

  def work_params
    params.require(:work).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end
end

app/controllers/company/resumes_controller.rb
class Company::ResumesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_recruiter

 def index
   @work = Work.find(params[:work_id])
   @resumes = @work.resumes.order('created_at DESC')
 end
 
end

app/controllers/company/works_controller.rb
class Company::WorksController < ApplicationController
before_action :authenticate_user!
before_action :require_recruiter
before_action :get_notification

  def index
    @works = current_user.works
  end

  def show
    @work = Work.find(params[:id])
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    @work.user = current_user
    if @work.save
      redirect_to company_works_path
    else
      render :new
    end
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    if @work.update(work_params)
      redirect_to company_work_path(@work)
    else
      render :edit
    end
  end

    def destroy
      @work = Work.find(params[:id])
      @work.destroy
      redirect_to company_works_path
    end

  private

  def work_params
  params.require(:work).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
before_action :get_notification
  def index
    @works = case params[:order]
           when 'by_lower_bound'
             Work.where(is_hidden: false).order('wage_lower_bound DESC')
           when 'by_upper_bound'
             Work.where(is_hidden: false).order('wage_upper_bound DESC')
           else
             Work.where(is_hidden: false).order('created_at DESC')
           end
  end

  def show
    @work = Work.find(params[:id])
    #被隐藏的工作不可见
    if @work.is_hidden
      flash[:warning] = "This work already archieved"
      redirect_to root_path
    end
  end
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/company/resumes_helper.rb
module Company::ResumesHelper
end

app/helpers/company/works_helper.rb
module Company::WorksHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/company/works/edit.html.erb
<div class="row">
<div class="col-md-4 col-md-offset-4">
    <h2>修改职位</h2>

    <hr>
    <%= simple_form_for [:company,@work] do |f| %>
    <div class="form-group">
        <%= f.input :title, input_html: { class: "form-control"} %>
        <%= f.input :description, inpuut_html: { class: "form-control"} %>
        <%= f.input :wage_lower_bound, :label => "薪资下限" %>
        <%= f.input :wage_upper_bound, :label => "薪资上限" %>
        <%= f.input :contact_email %>
        <%= f.input :is_hidden %>
    </div>
    <%= f.submit "Sumbit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
    <% end %>
</div>
</div>

app/views/company/works/index.html.erb
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
  <div class="group">
    <%= link_to("加添职缺", new_company_work_path, class: "btn btn-primary pull-right") %>
  </div>
  <div class="group" style="margin-top:50px;">
  <table class="table table-hover">
    <thead>
      <tr>
        <td>编号</td>
        <td>职缺</td>
        <td>职缺介绍</td>
        <td>收到简历数量</td>
      </tr>
    </thead>
    <tbody>
      <% @works.each do |work| %>
        <tr>
          <% n =+ 1 %>
          <td><%= work.id %></td>
          <td><%= link_to(work.title, company_work_path(work)) %></td>
          <td><%= work.description %></td>
          <td> <%= link_to(work.resumes.count, company_work_resumes_path(work)) %> </td>
          <td>
              <%= link_to("编辑", edit_company_work_path(work), class: "btn btn-sm btn-default")%>
              <%= link_to("删除", company_work_path(work),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>
</div>
</div>

app/views/company/works/new.html.erb
<div class= "row" >
<div class="col-md-4 col-md-offset-4">
    <h2>新增职位</h2>

    <hr>
    <%= simple_form_for [:company,@work] do |f| %>
    <div class="form-group">
        <%= f.input :title, :label => "职缺" %>
        <%= f.input :description, :label => "职缺介绍" %>
        <%= f.input :wage_lower_bound, :label => "薪资下限" %>
        <%= f.input :wage_upper_bound, :label => "薪资上限" %>
        <%= f.input :contact_email, :label => "联系邮箱"%>
        <%= f.input :is_hidden %>
    </div>
    <%= f.submit "Sumbit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
    <% end %>
</div>
</div>

app/views/company/works/show.html.erb
<div class="col-md-12">
  <h2><%= @work.title %></h2>
  <p><%= @work.description %></p>
</div>