config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :registrations => "registrations" }

resources :conversations, only: [:index, :show, :destroy] do
     member do
       post :reply
       post :restore
       post :mark_as_read
     end
     collection do
       delete :empty_trash
     end
end

 resources :users, only: [:index]

 resources :messages, only: [:new, :create]

 resources :works, only: [:show, :index] do
   resources :resumes, only: [:new, :create]
 end

 resources :applies, only: [:new, :create]

  namespace :company do
    resources :works do
      resources :resumes
    end
  end

  resources :notifications, only: [] do
    member do
      get :redirect_notification
    end
  end

  namespace :admin do
    resources :applies, only: [:index, :show, :destroy] do
      member do
        post :failed
        post :passing
        post :application
      end
    end
    resources :works do
      member do
        post :publish
        post :hide
      end
    end
    resources :users, only: [:index, :show, :destroy] do
      member do
        post :admin
        post :user
      end
    end
  end

  root "works#index"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum status:{ user: 0, moderator: 1 }

  ROLES = {0 => :user, 1 => :admin, 2 => :moderator, 3 => :recruiter}# cancancan use
  attr_reader :role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :all_except, -> (user) {where.not(id: user)}
  has_many :works
  has_many :notifications
  has_many :resumes
  has_one :apply

  acts_as_messageable

  def mailboxer_email(object)
    email
  end

  def role?(role_name)
    role == role_name
  end

  def moderator?
    self.status == "moderator"
  end

  def recruiter?
    is_recruiter
  end

  def admin?
   is_admin
  end

  def admin!
    self.is_admin = true
    self.save
  end

  def user!
    self.is_admin = false
    self.save
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :require_is_admin
  before_action :get_notification
  layout "admin"
  def index
    @users = User.all_except(current_user)
  end

  def show
   @user = User.find(params[:id])
 end

 def destroy
   @user = User.find(params[:id])
   @user.destroy
   redirect_to admin_users_path
 end

 def change_admin
   @user = User.find(params[:id])
   @user.admin!
   redirect_to :back
 end


 def change_user
   @user = User.find(params[:id])
   @user.user!
   redirect_to :back
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user).order('created_at DESC')
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            <i class="fa fa-list-ol" aria-hidden="true"></i>
                            用户编号</th>
                        <th>
                            <i class="fa fa-envelope-o" aria-hidden="true"></i>
                            Email</th>
                        <!-- <th><i class="fa fa-clock-o" aria-hidden="true"></i> 注册时间<th> -->
                        <th class="center">
                            <i class="fa fa-cog" aria-hidden="true"></i>
                            控制台</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <% @users.each do |user| %>
                        <% if user.is_admin %>
                        <td>

                            <%= link_to admin_user_path(user) do %>
                            <i class="fa fa-user"></i>
                            <%= user.id %>
                            <% end %>

                        </td>

                    <% else %>
                        <td>
                            <%= link_to admin_user_path(user) do %>
                            <i class="fa fa-plane"></i>
                            <%= user.id %>
                            <% end %>
                            <% end %>
                        </td>

                        <td>
                            <%= user.email %>
                        </td>

                        <td class="center">
                            <% if user.is_admin %>
                            <%= link_to("成为User", user_admin_user_path(user), :method => :post, :class => "btn btn-xs btn-default outline") %>
                        <% else %>
                            <%= link_to("成为Admin", admin_admin_user_path(user), :method => :post, :class => "btn btn-xs btn-default outline") %>
                            <% end %>

                            <%= link_to("删除", admin_user_path(user), method: :delete, :class => "btn btn-xs btn-default outline",:data => { :confirm => "确定要删除此用户？？" }) %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="text-center">
                <%#= will_paginate @users ,renderer: BootstrapPagination::Rails%>
            </div>
        </div>
    </div>

</div>