config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :registrations => "registrations" }

resources :conversations, only: [:index, :show, :destroy] do
     member do
       post :reply
       post :restore
       post :mark_as_read
     end
     collection do
       delete :empty_trash
     end
end

 resources :users, only: [:index]

 resources :messages, only: [:new, :create]

 resources :works, only: [:show, :index] do
   resources :resumes, only: [:new, :create]
 end

 resources :applies, only: [:new, :create]

  namespace :company do
    resources :works do
      resources :resumes
    end
  end

  resources :notifications, only: [] do
    member do
      get :redirect_notification
    end
  end

  namespace :admin do
    resources :applies, only: [:index, :show, :destroy] do
      member do
        post :failed
        post :passing
        post :application
      end
    end
    resources :works do
      member do
        post :publish
        post :hide
      end
    end
    resources :users, only: [:index, :show, :destroy] do
      member do
        post :admin
        post :user
      end
    end
  end

  root "works#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def current_ability
    @current_ability ||= Ability.new(current_user)
  end

  def initialize(user)
    user ||= User.new

    if user.admin?
       can :manage, :all
    elsif user.moderator?
       can :read, Work
    elsif user.role?(:user)
       can :read, Work
    elsif user.role?(:recruiter)
       can [:create, :read, :update], Work
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, ImageUploader
  has_many :photos
  accepts_nested_attributes_for :photos

  include AASM

  aasm do
    state :apply_sended, initial: true
    state :apply_passing
    state :apply_passed
    state :apply_failed

    event :passing do
      transitions from: :apply_sended, to: :apply_passing
    end

    event :passed do
      transitions from: :apply_passing, to: :apply_passed
    end

    event :failed do
      transitions from: :apply_passing, to: :apply_failed
    end
  end

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
  belongs_to :recipient, :class_name => "User"
  belongs_to :trigger, :class_name => "User"
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :apply
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :work
  mount_uploader :attachment, AttachmentUploader
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum status:{ user: 0, moderator: 1 }

  ROLES = {0 => :user, 1 => :admin, 2 => :moderator, 3 => :recruiter}# cancancan use
  attr_reader :role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :all_except, -> (user) {where.not(id: user)}
  has_many :works
  has_many :notifications
  has_many :resumes
  has_one :apply

  acts_as_messageable

  def mailboxer_email(object)
    email
  end

  def role?(role_name)
    role == role_name
  end

  def moderator?
    self.status == "moderator"
  end

  def recruiter?
    is_recruiter
  end

  def admin?
   is_admin
  end

  def admin!
    self.is_admin = true
    self.save
  end

  def user!
    self.is_admin = false
    self.save
  end

end

app/models/work.rb
class Work < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}
  has_many :resumes, dependent: :destroy
  has_many :notifications, as: :notifiable
  belongs_to :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user).order('created_at DESC')
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
before_action :get_notification
  def index
    @works = case params[:order]
           when 'by_lower_bound'
             Work.where(is_hidden: false).order('wage_lower_bound DESC')
           when 'by_upper_bound'
             Work.where(is_hidden: false).order('wage_upper_bound DESC')
           else
             Work.where(is_hidden: false).order('created_at DESC')
           end
  end

  def show
    @work = Work.find(params[:id])
    #被隐藏的工作不可见
    if @work.is_hidden
      flash[:warning] = "This work already archieved"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_header(text)
    content_for(:page_header) { text.to_s }
  end
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    options_for_select(User.where.not(:id => current_user.id).map { |user| [user.email, user.id,] }, chosen_recipient.nil? ? nil : chosen_recipient.id)
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 丢手绢
        <br>Design by
        <a href="http://javplay.com/model/mei-matsumoto/" target=_new>zs</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">爱聘</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                  <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       <i class="fa fa-bell"></i>&nbsp;通知
                       <b class="caret"></b>
                   </a>
                   <% if @notifications.present? %>
                     <% @notifications.each do |notification| %>
                      <% if notification.read_at == nil %>
                        <ul class="dropdown-menu">
                          <li>
                            <%= link_to redirect_notification_notification_path(notification) do %>
                              <span>
                                用户<%= notification.trigger.id %>
                                发送了简历
                              </span>
                              <% end %>
                          </li>
                        </ul>
                      <% end %>
                    <% end %>
                  <% end %>
                </li>
                  <% if current_user &&  current_user.admin? %>
                  <li><%= link_to("超级后台", admin_users_path) %></li>
                  <% end %>
                  <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登入", new_user_session_path) %></li>
                  <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <% if can? :create, Work %>
                        <li> <%= link_to("公司后台", company_works_path)  %></li>
                        <ul class="divider"></ul>
                        <% end %>
                        <li><%= link_to '信箱', conversations_path %></li>
                        <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>